spring:
  application:
    name: employee-service
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/employeedb}
      auto-index-creation: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null

server:
  port: 8081

logging:
  level:
    com.learning.employee: DEBUG
    org.springframework.data.mongodb: DEBUG
